# YOUR NAME OR TITLE OF YOUR SITE
name: juvelim

# YOUR BRAND/PERSONAL TAGLINE
tagline: Juventud de Iglesia de Cristo Elim Central



# YOUR/BRAND IMAGE URL
Image_URL: ./assets/images/juve.jpg

#https://images.unsplash.com/photo-1632171962729-ae5999222681?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1604&q=80

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://source.unsplash.com/featured/?worship

  #https://source.unsplash.com/random

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK

    # FACEBOOK
  - Name: Facebook
    URL: https://www.facebook.com
    Username: JUVELIMGuatemala
    Color: '#1877f2'
    Icon-Class: fab fa-facebook

    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: juvelim_guate
    Color: '#c32aa3'
    Icon-Class: fab fa-instagram


    # YOUTUBE
  - Name: YouTube
    URL: https://www.youtube.com/c
    Username: Radio760AMElimCentral
    Color: '#ff0000'
    Icon-Class: fab fa-youtube


    # SPOTIFY
  - Name: Spotify
    URL: https://open.spotify.com/artist
    Username: 5VHQgdumqij6OuSNFDPOn8
    Color: '#1ed760'
    Icon-Class: fab fa-spotify

    # EMAIL
  - Name: Envíanos un correo
    URL: 'mailto:juvelimguatemala@elimcentral.org'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'


    # MESSENGER
  - Name: Comunicate vía Messenger
    URL: https://m.me
    Username: JUVELIMGuatemala
    Color: '#3b5998'
    Icon-Class: fab fa-facebook-messenger


  #   # WHATSAPP
  # - Name: WhatsApp
  #   URL: https://wa.me
  #   Username: '+1123456789'
  #   Color: '#25d366'
  #   Icon-Class: fab fa-whatsapp





# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'Yes'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
baseurl: /links

# Default Markdown Engine
markdown: kramdown

url: https://github.com/jmarcos-cano/links.git
